apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vyn8f0zx4-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vyn8f0zx4-java-springboot-gitops